name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  xcode_16_3:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.3.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests --enable-code-coverage 
      - name: Test
        run: swift test --skip-build --enable-code-coverage
      - name: Gather code coverage
        run: xcrun llvm-cov export -format="lcov" .build/debug/identifiable-macroPackageTests.xctest/Contents/MacOS/identifiable-macroPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov

  linux_swift_6_1:
    runs-on: ubuntu-latest
    container: swift:6.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests --enable-experimental-prebuilts
      - name: Test
        run: swift test --skip-build

  linux_swift_6_0:
    runs-on: ubuntu-latest
    container: swift:6.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build

  linux_swift_5_10:
    runs-on: ubuntu-latest
    container: swift:5.10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test --skip-build
